spring:
  profiles:
    Active: dev
---
server:
  port: 7001
#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称  如http://localhost/....
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #表示自己是注册中心
    service_url: #与eureka交互的页面，监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
server:
  port: 7001
#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: localhost #Eureka服务端的实例名称  如http://localhost/....
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #表示自己是注册中心
    service_url: #与eureka交互的页面，监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
