spring:
  profiles: Active:dev
---
server:
  port: 81

spring:
  profiles: dev
  application:
    name: springcloud-provider-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_platform?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 199898zhang
    
mybatis:
  #type-aliases-package: com.shu.model # 起别名，mybatis自动扫描bean对象。在mapper文件中resultype不用再加完全限定名。
  #config-location: classpath:mybatis/mybatis-config.xml #mapper的配置地址
  mapper-locations: classpath:mapper/*.xml #mapper的配置地址    

#Eureka的配置，注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-81 #实例id
  #info配置，监控信息配置
info:
  app.name: zcx-springcloud
  company.name: zcx.com
---
server:
  port: 8001

mybatis:
  type-aliases-package: com.zcx.springcloud.pojo # 起别名，mybatis自动扫描bean对象。在mapper文件中resultype不用再加完全限定名。
  config-location: classpath:mybatis/mybatis-config.xml #mapper的配置地址
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper的配置地址

spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 199898zhang

#Eureka的配置，注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #实例id
  #info配置，监控信息配置
info:
  app.name: zcx-springcloud
  company.name: zcx.com
