spring:
  profiles:
    Active: dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-config-dev

#Eureka的配置，注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-config-dev

#Eureka的配置，注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
